name: Build and Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Astro site
      run: npm run build

    - name: Copy files to production server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/scp-action@v1.0.0
      with:
        host: 157.180.48.235
        username: deploy_gh_ericteubertde
        key: ${{ secrets.SSH_DEPLOY_KEY }}
        source: "dist/*"
        target: "/var/www/ericteubert.de"
        strip_components: 1
